### ISSUE TITLE
Ejercicio fuera de carpeta de sprint

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-soluciones-alumnas#10]
Me parece que el ejercicio 4 de la sesión 2.12 estaría mejor dentro de la carpeta del sprint 2.

¿Que opinas @mariviru ?

**Comment by mariviru** [comment]
Hola, no tengo muy claro cómo hacerlo, me clono el repo y desde ahí lo muevo a la carpeta correspondiente?

**Comment by oneeyedman** [comment]
Deberías:
- Clonarte el repo
- Crearte una rama
- Ajustar carpetas y archivos para que el ejercicio esté donde debe
- Add, commit y push
- Lanzar un PR para que alguien lo revise

**Comment by mariviru** [comment]
Hecho

**Comment by nasivuela** [comment]
Solucionado en https://github.com/Adalab/dorcas-soluciones-alumnas/pull/18
